homepage:
  path: /
  controller: App\Controller\BlogController::index

article_add:
  path: /add
  controller: App\Controller\BlogController::add

article_show:
  path: /show/{id}
  controller: App\Controller\BlogController::show

article_edit:
  path: /edit/{id}
  controller: App\Controller\BlogController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\BlogController::remove
  requirements:
    id: '\d+'

page_news:
  path: /news
  controller: App\Controller\BlogController::news

video_add:
  path: /video/add
  controller: App\Controller\BlogController::video_add

page_match:
  path: /match
  controller: App\Controller\BlogController::match

video_show:
  path: /video/show/{id}
  controller: App\Controller\BlogController::video_show

video_remove:
  path: video/remove/{id}
  controller: App\Controller\BlogController::video_remove

 

video_edit:
  path: /video/edit/{id}
  controller: App\Controller\BlogController::video_edit


video_index:
  path: /video
  controller: App\Controller\BlogController::video_index



admin:
  path: /admin
  controller: App\Controller\BlogController::admin

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

admin_remove_user:
  path: /remove/user/{id}
  controller: App\Controller\RegistrationController::removeUser